CREATE SCHEMA AUTHDB;

CREATE TABLE AUTHDB.USERS
(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(64) NOT NULL,
	USERNAME VARCHAR(64) NOT NULL,
	PASSWORD VARCHAR(128) NOT NULL,
	ROLE VARCHAR(64),
	CONSTRAINT USERS_USERNAME_UINDEX UNIQUE (USERNAME)
);

INSERT INTO AUTHDB.USERS (ID, NAME, USERNAME, PASSWORD, ROLE) VALUES (1, 'Administrator', 'admin', 'admin', 'admin');
INSERT INTO AUTHDB.USERS (ID, NAME, USERNAME, PASSWORD, ROLE) VALUES (2, 'User', 'user', 'user', 'user');
INSERT INTO AUTHDB.USERS (ID, NAME, USERNAME, PASSWORD, ROLE) VALUES (3, 'Guest', 'guest', 'guest', 'admin');
